defaults:
  - default

network: null

variance_schedule:
  _target_: src.model_components.variance_schedule.VarianceSchedule
  num_steps: &time_steps 1000
  beta_1: 1e-4
  beta_T: 0.05
  mode: linear

# dataset 
dataset_kwargs:
  data_path: ${data_3d.latent_path}
  repeat: 6
  only_easy_context: false
  global_normalization: ${model.global_normalization}


# model
global_normalization: false
text_encoder_freeze: false
use_lstm: true
classifier_free_guidance: true
conditioning_dropout_prob: 0.2

# Evaluation
stage1_model_path: ${stage1_model_path}

spaghetti_tag: ${data_3d.spaghetti_tag}