model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 1

#rich_progress_bar:
#  _target_: pytorch_lightning.callbacks.RichProgressBar
#  leave: false
#  theme:
#    _target_: pytorch_lightning.callbacks.progress.rich_progress.RichProgressBarTheme
#    description: "green"
#    progress_bar: "green1"
#    progress_bar_finished: "green1"
#    progress_bar_pulse: "#6206E0"
#    batch_progress: "green"
#    time: "grey82"
#    processing_speed: "grey82"
#    metrics: "grey82"
#    metrics_text_delimiter: "\n"
#    metrics_format: ".3e"

tqdm_progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  leave: false
  refresh_rate: 1

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "train/loss"
  mode: "min"
  save_top_k: 1
  save_last: true
  verbose: true
  dirpath: "checkpoints/"
  filename: "epoch:{epoch:02d}-train_loss:{train/loss:.4f}"
  every_n_epochs: 100
  auto_insert_metric_name: false

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "step"

