defaults:
  - default

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "train/total_loss"
  mode: "max"
  save_top_k: 1
  save_last: true
  verbose: true
  dirpath: "checkpoints/"
  filename: "epoch:{epoch:02d}-train_loss:{train/loss:.4f}"
  every_n_epochs: 100
  auto_insert_metric_name: false
